### ISSUE TITLE
Exception on unnamed exports

### ISSUE THREAD

**Issue by macgeiger** [guelfoweb/peframe#12]
When processing a PE file with exports that are unnamed (referenced only by ordinal value), peframe will throw the following exception because func['function'] contains None.

  File "/usr/lib/python2.7/site-packages/peframe-5.0-py2.7.egg/peframe/peframe.py", line 362, in stdoutput
    print func['function'][0:15].ljust(15), func['address']
TypeError: 'NoneType' object has no attribute '__getitem__'

Depending on where you want to address this, one solution would be around line 361:
`for func in output['pe_info'][item]:`
      `if func['function'] is None:`
             `print "Unnamed export".ljust(15), func['address']`
       `else:`
              `print func['function'][0:15].ljust(15), func['address']`

Thanks.

**Comment by guelfoweb** [comment]
Hi macgeiger, can you send the sample to check the error?
Thanks.

**Comment by macgeiger** [comment]
I can't share the actual file, but have found a similar one that creates the same issue. See attached.
[a.zip](https://github.com/guelfoweb/peframe/files/161623/a.zip)

**Comment by guelfoweb** [comment]
Ok, I have fixed it. Thanks for suggestion!

**Comment by macgeiger** [comment]
And thank you for the quick response and, of course, peframe.
